services:
  - mysql
before_install:
  - mysql -e 'create database dsmanager;'

install:
  - cd api/ && composer install --prefer-dist --no-interaction
  - php novice migrate

language: php

notifications:
  email: false
